namespace Notes;

public enum TokenType
{
    LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_PAREN, RIGHT_PAREN,
    OCTOTHORPE,
    STAR,
    STAR_SPACE,
    UNDERSCORE,
    GREATER,
    BANG,
    NUMBER_DOT,
    BACKTICK,
    TRIPLE_BACKTICK,
    BACKSLASH,
    TEXT,
    EOF
}